/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class annoy4j_AnnoyJNI */

#ifndef _Included_annoy4j_AnnoyJNI
#define _Included_annoy4j_AnnoyJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     annoy4j_AnnoyJNI
 * Method:    alloc
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_annoy4j_AnnoyJNI_alloc
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     annoy4j_AnnoyJNI
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_annoy4j_AnnoyJNI_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     annoy4j_AnnoyJNI
 * Method:    addItem
 * Signature: (JI[F)V
 */
JNIEXPORT void JNICALL Java_annoy4j_AnnoyJNI_addItem
  (JNIEnv *, jclass, jlong, jint, jfloatArray);

/*
 * Class:     annoy4j_AnnoyJNI
 * Method:    build
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_annoy4j_AnnoyJNI_build
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     annoy4j_AnnoyJNI
 * Method:    save
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_annoy4j_AnnoyJNI_save
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     annoy4j_AnnoyJNI
 * Method:    unload
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_annoy4j_AnnoyJNI_unload
  (JNIEnv *, jclass, jlong);

/*
 * Class:     annoy4j_AnnoyJNI
 * Method:    load
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_annoy4j_AnnoyJNI_load
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     annoy4j_AnnoyJNI
 * Method:    getDistance
 * Signature: (JII)F
 */
JNIEXPORT jfloat JNICALL Java_annoy4j_AnnoyJNI_getDistance
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     annoy4j_AnnoyJNI
 * Method:    getNnsByItem
 * Signature: (JIII[I[F)V
 */
JNIEXPORT void JNICALL Java_annoy4j_AnnoyJNI_getNnsByItem
  (JNIEnv *, jclass, jlong, jint, jint, jint, jintArray, jfloatArray);

/*
 * Class:     annoy4j_AnnoyJNI
 * Method:    getNnsByVector
 * Signature: (J[FII[I[F)V
 */
JNIEXPORT void JNICALL Java_annoy4j_AnnoyJNI_getNnsByVector
  (JNIEnv *, jclass, jlong, jfloatArray, jint, jint, jintArray, jfloatArray);

/*
 * Class:     annoy4j_AnnoyJNI
 * Method:    getNItems
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_annoy4j_AnnoyJNI_getNItems
  (JNIEnv *, jclass, jlong);

/*
 * Class:     annoy4j_AnnoyJNI
 * Method:    verbose
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_annoy4j_AnnoyJNI_verbose
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     annoy4j_AnnoyJNI
 * Method:    getItem
 * Signature: (JII)[F
 */
JNIEXPORT jfloatArray JNICALL Java_annoy4j_AnnoyJNI_getItem
  (JNIEnv *, jclass, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
